version: 2.1

######################################################################################################################
# Define the ORBS we'll use in the rest of the workflow
######################################################################################################################
orbs:
  docker: circleci/docker@0.5.13
  awscli: circleci/aws-cli@0.1.13
  slack: circleci/slack@3.4.1
  python: circleci/python@0.3.0
  ruby: circleci/ruby@1.0.0

######################################################################################################################
# We define all the actual build steps here in named, reusable references. This allows us to define jobs below as a
# readable, composable list of references
######################################################################################################################
references:
  base_container: &base_container
    docker:
      - image: circleci/ruby:2.6.2-stretch

  ######################################################################################################################
  # Build steps
  ######################################################################################################################
  install_pip: &install-pip
    run:
      name: install pip
      command: |
        set +o pipefail
        curl -O https://bootstrap.pypa.io/get-pip.py
        sudo python3 get-pip.py

  deploy_to_staging: &deploy-to-staging
    run:
      name: deploy to staging
      command: |
        set +o pipefail
        if [[ "$CIRCLE_BRANCH" == "master" ]]; then
          echo "on master, deploying to staging"
        else
          echo "not on master, skipping staging deploy"
        fi

  deploy_to_prod: &deploy-to-prod
    run:
      name: deploy to prod
      command: |
        set +o pipefail
        echo "on tag, deploying to prod"

  notify_slack: &notify_slack_on_failure
    slack/status:
      fail_only: true
      failure_message: ":red_circle: $CIRCLE_JOB has failed on master! Build triggered by: $CIRCLE_USERNAME. You have one hour to fix or revert!!"
      only_for_branches: "master"

#######################################################################################################################
# The build jobs available, all consisting of lists of references to the references section above
#######################################################################################################################
jobs:
  deploy-to-stage:
    <<: *base_container
    description: Deploy to Staging
    steps:
      - checkout
      - setup_remote_docker
      - *install-pip
      - awscli/install
      - *deploy-to-staging
      - *notify_slack_on_failure

  deploy-to-prod:
    <<: *base_container
    description: Deploy to Prod
    steps:
      - checkout
      - setup_remote_docker
      - *install-pip
      - awscli/install
      - *deploy-to-prod
      - *notify_slack_on_failure

# ---------------------------------------------------------------------------------------------------------------------
# Here we combine the jobs defined above into various workflows that can run in parallel or sequentially, define
# dependencies on each other, and only run on certain branches/tags.
# ---------------------------------------------------------------------------------------------------------------------

workflows:
  version: 2
  each_commit:
    jobs:
      - deploy-to-stage:
          filters:
            branches:
              only: master
      - deploy-to-prod:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
